openapi: 3.0.0
info:
  title: Oxytrack API
  version: 0.1.0
servers:
  - url: "{protocol}://{hostname}/api/v1"
    variables:
      protocol:
        default: "http"
      hostname:
        default: "localhost:3000"
components:
  schemas:
    $ref: "./schemas/index.yaml"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Master User
    description: Master User related operations
  - name: Contact
    description: Contact related operations
  - name: Ambulance
    description: Ambulance related operations
paths:
  /masterUser/signIn:
    $ref: "./paths/masterUser/masterSignIn.yaml"
  /contacts:
    $ref: "./paths/contact/createContact.yaml"
  /customer/ambulance:
    $ref: "./paths/customers/ambulance/ambulance.yaml"
