openapi: 3.0.0
info:
  title: Contract for tenant-api
  version: 0.1.0
components:
  schemas:
    $ref: "./schemas/index.yaml"
paths:
  /masterUser/signIn:
    $ref: "./paths/masterUser/masterSignIn.yaml"
  /customer/ambulance:
    $ref: "./paths/customers/ambulance/ambulance.yaml"