openapi: 3.0.0
info:
  title: Oxytrack API
  version: 0.1.0
components:
  schemas:
    $ref: "./schemas/index.yaml"
paths:
  /masterUser/signIn:
    $ref: "./paths/masterUser/masterSignIn.yaml"
  /customer/ambulance/create:
    $ref: "./paths/customers/ambulance/ambulanceCreate.yaml"